runs:
  using: "composite"
  steps:
    - name: Print install-pip-deps
      run: echo Installing pip dependencies
    - name: Clone python-greetings
      run: git clone https://github.com/mtararujs/python-greetings ./python-greetings
    - name: Check python-greetings directory
      run: |
        cd python-greetings
        dir
    - name: Install pip dependencies
      run: |
        cd python-greetings
        pip install -r requirements.txt