name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
  workflow_dispatch:

jobs:
  hello:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Print greeting
        run: echo Hello, world!
  node-version:
    runs-on: npm
    steps:
      - uses: actions/checkout@v3
      - name: Check node version
        run: node --version
